### ISSUE TITLE
✨ 下載到後面會降速嗎

### ISSUE THREAD

**Issue by w0853** [SigureMo/bilili#100]
## 是否愿意为此贡献代码

我今天才安裝v1.4.8,bilili https://www.bilibili.com/bangumi/play/ep380634
下載19,20集後晚上8pm開始降的原本600多k變5k以下在跑
是有下載影片數目限制嗎(1天以內)?
順帶一題降速時我開網頁測試發現網頁開的不慢,也下檔案測試也是500~600k在跑
還有明明19集檔案大小只有233.2mb,跑的量卻超過了?!
https://imgur.com/a/1nQF8y7

**Comment by SigureMo** [comment]
> 下載19,20集後晚上8pm開始降的原本600多k變5k以下在跑

由于前期视频较多，而且每个视频都能分成多块，所以可以将多个块分发到多个线程去下载，这使得前期速度是非常快的。但到了后期，剩余视频分块数小于最大线程数时，就无法充分利用多线程的优势了，所以速度会明显降低，并不是下载限制相关问题。（当然也许可能有限制，但我没触发过）

> 還有明明19集檔案大小只有233.2mb,跑的量卻超過了?!

这个问题我也不太清楚😂，刚刚我挂代理下载没有出现这个问题，可能是连接不佳导致的一系列问题。

如果最后是因为某两个块连接不佳导致下载迟迟无法完成的话，可以尝试手动删除这两个块（.dl 后缀的文件），默认块大小为 128MiB，可以认为非 128MiB 的块是未下载完成的块。删除之后重新运行（不启用 overwrite 选项）就可以触发断点续传继续下载。
