### ISSUE TITLE
✨ 除了命令行 请问有打算提供python接口吗

### ISSUE THREAD

**Issue by sunset1234321** [SigureMo/bilili#114]
还是比较习惯在python调用函数...

有几个影片特别想下载收藏   一个一个命令行太累了

**Comment by SigureMo** [comment]
目前并没有相关计划，如果一定要 python 调用的话可以尝试 subprocess

> 有几个影片特别想下载收藏 一个一个命令行太累了

这个可以通过 shell 脚本进行批处理，比如在 yutto discussion 里提到的这样 https://github.com/SigureMo/yutto/discussions/6

再或者 yutto（bilili 2.0） 里提供了通过自定义文件列表进行批量下载的方式
