### ISSUE TITLE
✨ 添加8K视频下载支持

### ISSUE THREAD

**Issue by xincheng213618** [SigureMo/bilili#124]
video_quality_map 127:{
"description": "超高清 8K",
"width": 8192,
"height": 4320,
},
play_api_dash = play_api + "&fnver=0&fnval=2000&fourk=1"
设定初始qulity 为127 即可

**Comment by SigureMo** [comment]
可以使用 [yutto（bilili2.x）](https://github.com/SigureMo/yutto)，已经支持 8K 了

当然如果需要 bilili 支持的话，欢迎 PR

**Comment by xincheng213618** [comment]
好滴
