### ISSUE TITLE
💬 Feedback

### ISSUE THREAD

**Issue by SigureMo** [SigureMo/bilili#23]
https://bilili.sigure.xyz/guide/feedback.html

**Comment by kakaisjr** [comment]
我发现还是ubnutu好使，我win10到现在都没搭建好twt

**Comment by SigureMo** [comment]
@kakaisjr 对的，*nix 安装这些都非常方便，win 就需要很麻烦……不过只要配置好环境变量也是可以用的

**Comment by SigureMo** [comment]
@kemistep 用 python3.8 及以上版本

**Comment by suay1113** [comment]
建议python环境写到readme里面，许多人用的python3.7以下版本，会报错

**Comment by SigureMo** [comment]
@suay1113 有注明啊，第二个 Badge 就是啊，而且网页版文档里也写了

**Comment by SigureMo** [comment]
emmm，我在程序中添加一下吧，低于 3.8 提示版本问题并直接退出

**Comment by CN-NULL** [comment]
打扰了，请问，没关闭视频下载这一选项，是吗？只想下载弹幕，对视频没有需求。我在命令行参数里似乎没有找到视频下载的开关，只有弹幕下载的开关。
