### ISSUE TITLE
✨ 增加对外 API

### ISSUE THREAD

**Issue by SigureMo** [SigureMo/bilili#24]
## 特性描述

添加外部 API，支持通过 Python 调用和 WSGI 方式（部署到 vercel）引用

## 是否愿意为此贡献代码

WIP

**Comment by SigureMo** [comment]
由于最近 B 站外链加上 `high_quailty=1` 也只能最高 480P，因此考虑使用 B 站 MP4 API 搭配 DPlayer 来做外链，但……跨域，所以想利用 bilili 已有的 API 做一个外部 API，以提供给外链使用

因此需要

- [ ] API 代码解耦
- [x] [Vercel API 探索](https://github.com/SigureMo/bilili-api-test)

**Comment by SigureMo** [comment]
另外现在尚不支持同一 Repo 多次 Import（同时部署文档和 API），所以需要等等

https://github.com/vercel/vercel/discussions/4719

**Comment by chorylee** [comment]
WSGI 调用很有用，但是目前这个API： https://bilipi.sigure.xyz/api/v0/acg_video/playurl 中不支持page参数，不知道是否能够加上

**Comment by SigureMo** [comment]
> WSGI 调用很有用，但是目前这个API： https://bilipi.sigure.xyz/api/v0/acg_video/playurl 中不支持page参数，不知道是否能够加上

page 的语义是指列表中第 n 个 video 吗？

如果是的话，可以先调用 list 方法，获取第 n 个视频的 cid，之后再传入 playurl 方法。

由于本 API 只针对 bilili 的下载流程而设计，所以很多方面没有考虑到，我是不太建议使用它的，未来很可能删掉 WSGI 调用方式（至少现在的计划是这样）。

**Comment by Yuelioi** [comment]
> 因为最近B站外链加上`high_quailty=1`也只有最高480P，所以考虑使用B站MP4 API搭配DPlayer来做外链，但……跨域，所以想利用bilili以前的API做一个外部API，以提供给外链使用
> 
> 因此需要
> 
> * [x]  API 代码解耦
> * [x]  [Vercel API 探索](https://github.com/SigureMo/bilili-api-test)

大佬，外链高清画质问题，请问现在有啥好办法么

**Comment by SigureMo** [comment]
可以自己用 Vercel 搭建一个高清 mp4 链接解析的 API，bilili 的对外 API 已经被移除了
