### ISSUE TITLE
💬 关于代码结构为什么这么烂这档子事

### ISSUE THREAD

**Issue by loliconRoot** [SigureMo/bilili#33]
## 特性描述

1. 命令行是对大多数人不友好的，希望能够有一个交互式的UI（GUI还是算了，太麻烦...）。（ps:我对友好的UI有一种特别的执念，所以我也希望bilili有一个友好的UI）
2. 我想一个静态的配置文件是很有帮助，json是一个不错的选择（尤其是ffmpeg的路径...）。
3. BilibiliAPI的调用方式总会让我有种“一些使用这个包的代码会触发服务器的防御机制”的感觉，希望可以提高一下返回值的可重用性....
4. 希望可以对UP主的投稿视频进行处理。
---
###ps:
> 因为之前花寄的事，我加急敲了个爬虫，下载器还是引用别人的。
> 即使如此这个程式还是只能用惨不忍睹来形容。所以我打算重写一个。
> 当我使用  
> ``pip search bili`  
> 的时候，我发现了'bilili'。它的代码的整洁性令我惊叹,而那极其不友好的使用方式亦让我惊讶。
> 所以我来的了Github并发起了Issues，希望可以将我的想法传达给作者

###ps2:
> 头一回使用Github，如果让你产生了什么不好的感受或者我有什么不对的地方希望可以告诉我  
> 不擅长和人交流，见笑了(- _ -)

## 是否愿意为此贡献代码

我已经fork了这份项目，但是我的python技术并不是特别好，所以分析代码的架构和修改可能花费不少时间  
我希望也能为bilili出一份力  
希望作者不要介意参考bilili的设计思路和部分源码并将其用在我的项目上

**Comment by SigureMo** [comment]
感谢你的反馈～

> 命令行是对大多数人不友好的，希望能够有一个交互式的UI（GUI还是算了，太麻烦...）。（ps:我对友好的UI有一种特别的执念，所以我也希望bilili有一个友好的UI）

是说界面整洁性提升还是交互性提升呢？据我所指大多数命令行工具都是一次性指定参数进行工作的，太多的交互反而不利于熟悉 CLI 的人使用，而且也对自动化调用不利，举个例子

``` bash
# 现在的 bilili 只需要这样就可以下载最新一话的内容
bilili <url> -y -p $ --playlist-type=m3u
# 如果是交互式
bilili <url>
> 请输入 url: <url>
> 请输入 episode: $
> 请输入播放列表类型: m3u
> 请确认下载: y
> ...
# 这样就非常麻烦……，而且你是没有办法通过命令去调用的
```

我现在的用法是这样的，在 shell 中添加下面这条 `alias`

``` bash
alias bll='bilili -d ~/视频/ -c \"$(cat $HOME/bilili.sessdata)\" --disable-proxy --danmaku=ass --playlist-type=m3u -y --use-mirrors'
```

这样每次我下载的时候只需要输入 `bll <url>` 即可，非常方便，并不需要每次去记那些常用的参数，如果是交互式，就要一步一步去修改了

> 我想一个静态的配置文件是很有帮助，json是一个不错的选择（尤其是ffmpeg的路径...）。

这个我会考虑，但我的考虑仅限于 `sessdata` 的存储，其他的……感觉没有需要存储的啊，ffmpeg 也不需要配置路径啊，加入环境变量 PATH 一劳永逸啊，甚至其他程序都能直接访问

> BilibiliAPI的调用方式总会让我有种“一些使用这个包的代码会触发服务器的防御机制”的感觉，希望可以提高一下返回值的可重用性....

这里没懂……BiliPI 暂时只是测试用的，不太建议使用……目前我只是为了做文档的视频外链而使用，以后可能移除……

> 希望可以对UP主的投稿视频进行处理。

是说批量下载某个 UP 主的视频是吗，由于这个必然会再出现一层循环，因此暂时只能循环调用 bilili，等以后支持多 url 的时候会一并支持，但不知道会是何年

> 它的代码的整洁性令我惊叹,而那极其不友好的使用方式亦让我惊讶。

代码整洁性不敢说，因为现在仍然还是很乱，但我近期不打算大规模重构

emmm，使用方式我觉得还蛮简单的233

> 希望作者不要介意参考bilili的设计思路和部分源码并将其用在我的项目上

这个请遵守 GPL-3.0 协议，协议内容我就不多说了，至于我的协议为什么是 GPL-3.0 我的文档里也说了

具体问题可以继续讨论喔

**Comment by loliconRoot** [comment]
emmm...抱歉，这是我没有说清楚。
> 这个我会考虑，但我的考虑仅限于 sessdata 的存储，其他的……感觉没有需要存储的啊，ffmpeg 也不需要配置路径啊，加入环境变量 PATH 一劳永逸啊，甚至其他程序都能直接访问

这个在交互式的环境中有更明显的作用，例如当用户想要修改默认值的时候可以：  
1. 修改配置文件
2. 指定新的配置文件
3. 通过交互式命令修改静态的默认配置
4. 通过交互式命令修改动态的默认配置

硬编码在代码中的默认值改起来着实麻烦...-_-||

> 是说界面整洁性提升还是交互性提升呢？据我所指大多数命令行工具都是一次性指定参数进行工作的，太多的交互反而不利于熟悉 CLI 的人使用，而且也对自动化调用不利

命令行指定参数和交互式其实各有利弊。而且并不是说采用交互式就一定舍弃了命令行，比如将交互式接口做成一个模块，通过参数调用，比如‘-G’。
而且正如你在文档中描述的：
> 这里使用的序号是视频的顺序序号，而不是番剧所标注的第 n 话，因为有可能会出现 第 x.5 话 等等的特殊情况，此时一定要按照顺序自行计数。

在交互式界面完全可以打印一些信息，像：
```
公主连结！Re:Dive    PageID:2379
======================================================================================================================
|-id-|---------------------name---------------------|----------------------------------------------------------------|
|0000|第1话 公主连结01                              |/play/2379-1.html                                               |
|0001|第2话 公主连结02                              |/play/2379-2.html                                               |
|0002|第3话 公主连结03                              |/play/2379-3.html                                               |
|0003|第4话 公主连结04                              |/play/2379-4.html                                               |
|0004|第5话 公主连结05                              |/play/2379-5.html                                               |
|0005|第6话 公主连结06                              |/play/2379-6.html                                               |
|0006|第7话 公主连结07                              |/play/2379-7.html                                               |
|0007|第8话 公主连结08                              |/play/2379-8.html                                               |
|0008|第9话 公主连结09                              |/play/2379-9.html                                               |
|0009|第10话 公主连结10                             |/play/2379-10.html                                              |
|0010|第11话 公主连结11                             |/play/2379-11.html                                              |
|0011|第12话 公主连结12                             |/play/2379-12.html                                              |
|0012|第13话 公主连结13                             |/play/2379-13.html                                              |

Please select download entry:
'a' to download ALL,
'number' to download only one entry,
A numerical range(a-b) OR A range of values divided by ','(a-b,c-d) to download multiple entries.
```
可以有效的解决这种问题(个人意见，仅供参考)
> 这里没懂……BiliPI 暂时只是测试用的，不太建议使用……目前我只是为了做文档的视频外链而使用，以后可能移除……

我发现在bilili.api中，大部分函数每一次使用都会请求一次api.bilibili.com，但是为了防止api被滥用，B站似乎限制了同一IP在一定时间内访问次数，
一些不健康的使用方式可能导致这种后果（被禁IP）。而且BilibiliAPI返回的数据很多....实际上很大一部分（不常用的）数据被舍弃了，我在想是否有办法解决这个问题。

> 是说批量下载某个 UP 主的视频是吗，由于这个必然会再出现一层循环，因此暂时只能循环调用 bilili 实现，等以后支持多 url 的时候会一并支持，但不知道会是何年

因为这是特殊需求，所以可以添加一个函数实现。这里有一个API可能有所帮助：
```
https://api.bilibili.com/x/space/arc/search?mid={uid}&pn={pn}&ps=25&jsonp=jsonp
https://api.bilibili.com/x/space/arc/search?mid={uid}&ps=30&tid=0&pn={new_pn}&keyword=&order=pubdate&jsonp=jsonp
{
	"status": true,
	"data": {
		"//":"视频标签信息",
		"tlist": {
			"//":"标签id",
			"36": {
				"tid": 36,
				"//":"属该用户视频专栏中的第一个视频",
				"count": 1,
				"//":"转码后为‘科技’，标签名称",
				"name": "\u79d1\u6280"
			}
		},
		"vlist": [{
			"comment": 0,评论数
			"typeid": 122,
			"//":"播放量",
			"play": 40,
			"//":"视频封面",
			"pic": "\/\/i0.hdslb.com\/bfs\/archive\/d1f02d537abe71be9ab8ee0df97752dee35c3f44.jpg",
			"//":"副标题",
			"subtitle": "",
			"//":"视频介绍",
			"description": "https:\/\/blog.csdn.net\/weixin_42232219\/article\/details\/88548716?utm_source=app\n\u8f6c\u81ea\u56fd\u5916\u4eba\u5de5\u667a\u80fd\u9886\u57df\u7684\u7f16\u7a0b\u9ad8\u624bSiraj Raval\u3002",
			"//":"版权信息",
			"copyright": "",
			"//":"视频标题",
			"title": "[python]7\u884cPython\u4ee3\u7801\uff0c\u642d\u5efa\u4e00\u4e2a\u53ef\u4ee5\u8bc6\u82b1\u7684\u673a\u5668\u5b66\u4e60APP",
			"//":"",
			"review": 0,
			"//":"作者信息",
			"author": "bass\u65e0\u7ec8",
			"//":"视频编号",
			"mid": 43920592,
			"//":"视频是否联合出品",
			"is_union_video": 0,
			"//":"视频发布时间戳",
			"created": 1582314953,
			"//":"视频总长",
			"length": "05:03",
			"//":""历史累计弹幕数"",
			"video_review": 0,
			"//":"",
			"is_pay": 0,
			"aid": 90742233,
			"//":"显示隐藏",
			"hide_click": false
		}],
		"//":"空间内部GET获取",
		"count": 1,
		"pages": 1
	}
}
注：这个返回数据的模板是过时的，但是api是新的（昨天测试时可以用），我只是借用这个模板对返回值进行标记（标记已经修正过了）
```
实际上通过循环调用解决是很好的解决方案，因为如果并发数太多有可能被封IP（可能是我过于小心了）

> 代码整洁性不敢说，因为现在仍然还是很乱，但我近期不打算大规模重构

e...如果这样我的代码简直就无地自容了....实属乱套...所以我才会被惊到(^ _ ^)

> 这个请遵守 GPL-3.0 协议，协议内容我就不多说了，至于我的协议为什么是 GPL-3.0 我的文档里也说了

抱歉...我其实对这个是七窍通了六窍——一窍不通。(- _ -)||

---

感谢你能抽出时间回复我的问题，给你添麻烦了。

**Comment by SigureMo** [comment]
- 关于交互式

加上参数类似于 -G 这种方式来调用吗，这个可以考虑，但工作量可能不小

- 关于默认值的配置

emmm，考虑过，当时也是觉得每次输入参数太麻烦，但现在已经习惯这种方式了:joy:

以前在其他项目试验过类似工作，但最终我觉得好像真的没太大必要啊

而且还动态修改，这个交互的逻辑就很麻烦了，倒不是说难实现，而是说维护的成本就很高了，我现在觉得 bilili 的应该将逻辑更多放在 API 上，但现在其实更多放在了下载器逻辑，因此其实我并不太喜欢 bilili 现在的设计，当然将下载器完整地封装为一个模块是一个好的想法，但由于下载逻辑与 UI 逻辑中间需要一个状态的通信，所以我一直没想好怎么去封装她

- 关于 BiliPI

这个嘛，暂时只是针对 bilili 本身的，以其下载视频的频率我还没遇到过封 IP 的情况（不会你用这个都会被封了吧

当然也可以将其扩展为一个功能更强大的 API 包，但短期内我并没有这方面的计划，如果你对这方面感兴趣可以参考 [bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect)

- 关于 UP 主视频

对的，但这个的问题不在于实现难度，而是在于框架设计上，因为现在要支持两层结构还需要若干的改进，我不太希望为了新的功能而牺牲设计结构（虽然现在也不怎么样就是了

其实很多问题我都考虑过，但一些是已经放弃了（交互相关，我刚学那会比较喜欢，自从接触参数式调用后就再也喜欢不起来了），另外一些是在[遥远的计划 （比如 Roadmap 2.x）](https://github.com/SigureMo/bilili/projects/2)中（不一定会做，近期没有相关计划，我还需要去学习更多）

**Comment by loliconRoot** [comment]
* 关于默认值的配置和UP 主视频

其实2，3条可以很好地结合在一起，比如创建一个Setting类，从本地的json文件里读取默认值，然后作为参数传入一个封装的函数  
这个函数实现外层循环：读取UP主的投稿数据->提取信息->将配置和视频下载必要信息传入工作函数...它只需要做一个封装的工作

但是这种方式也许对现在的传参方式不太友好...它更像起到一个模块的作用——被其他脚本调用  

其实默认值设置更主要的一点是它提供了一个统一的入口来修改一些设置，这样是程序友好的并且利于二次开发，维护和一些重要参数改变的情况，比如api的改变或者爬虫规则的变更

所谓的动态修改主要指在另一个py程序调用时修改下载配置，程序中读取是静态的，动态的是配置文件（更好是类）的属性的值（一股PHP框架的既视感...）

* 关于 BiliPI

主要是大量的信息被丢弃了，事实上除了开发者或者有特殊需要的人来说是不必要的。（我只是想给它安个数据结构😂（强迫症犯了））

*  bilili 现在的设计

我需要一定时间来分析你的下载器，如果有可能，我会提出自己的意见（说实话，这个下载器着实有点乱，在与外界交互时尤为糟糕）

* 关于交互式

如上所述，我需要一点时间来分析源码，如果我有能力，我会试图给它安上一个交互接口。(说不定比你想得还简陋)  
相对的，我对于下载器的具体实现和媒体处理简直毫无头绪（事实上我完全没有接触过媒体处理方面的知识（- _ -||））

**Comment by SigureMo** [comment]
惊了，居然还没睡

**Comment by loliconRoot** [comment]
惊了，你居然也没睡

**Comment by SigureMo** [comment]
我……我日常啊……

正在看……如果你现在要睡了的话就快去睡吧～

**Comment by loliconRoot** [comment]
看到来邮件了就趴起来了...
说实话，比起让用户提供url来说，让用户可以选择提供aid或bvid比较好

**Comment by loliconRoot** [comment]
还有后面的uid/mid

**Comment by SigureMo** [comment]
喔，这个啊，这个是延续了之前做其他项目的习惯，url 其实也不是很麻烦啦，倒是分析那些 id 感觉对用户并不一定太友好

**Comment by SigureMo** [comment]
当然虽然 B 站用户人均知道 AVID 和 BVID

**Comment by loliconRoot** [comment]
毕竟哔哩哔哩是个例外....相应的还有Silisili和neita
有的时候命令行不能复制...敲url简直是一场灾难

**Comment by SigureMo** [comment]
啊？不能复制的命令行？我还没见过啊

**Comment by loliconRoot** [comment]
可以考虑将id作为带特殊前缀的参数

**Comment by SigureMo** [comment]
唉 这些的设计又需要考虑很久呢……

**Comment by loliconRoot** [comment]
确实少见...汗。
我记得有一次碰上这种情况，然后给我留下了深刻的印象，之后就尽量精简用户输入

**Comment by SigureMo** [comment]
> 其实默认值设置更主要的一点是它提供了一个统一的入口来修改一些设置，这样是程序友好的并且利于二次开发，维护和一些重要参数改变的情况，比如api的改变或者爬虫规则的变更

这里不太明白诶，能举个详细的例子吗

**Comment by loliconRoot** [comment]
的确，命令行分析永远令人头大...但是后面的不都是继承前面的参数吗，调整一下分析就行了吧

**Comment by SigureMo** [comment]
那个，如果你照常现在要去睡了的话就快去睡吧，明天有时间再讨论也可以

**Comment by loliconRoot** [comment]
> 这里不太明白诶，能举个详细的例子吗
比如如果B站的一个api被弃用了，但是返回值不变。或者另一个人应为不同的需求需要更改默认参数。亦或者一个人长期使用bilili下载到同一个目录。比起翻代码，有一个统一的文件来改变应用的设置是很友好的（很抱歉我想象匮乏难以形容）

**Comment by SigureMo** [comment]
> 如上所述，我需要一点时间来分析源码，如果我有能力，我会试图给它安上一个交互接口。(说不定比你想得还简陋)

关于交互，我觉得还是需要再次讨论一下，就目前看来我觉得必要性还是不太大，举例来说 you-get 这样的就是没有交互式的，bilili 的定位也类似，如果需要交互那直接用 GUI 就好了啊，唧唧那种下载器岂不是更好的选择，所以 bilili 一开始就没想做太多的交互

**Comment by SigureMo** [comment]
> 比如如果B站的一个api被弃用了，但是返回值不变。或者另一个人应为不同的需求需要更改默认参数。亦或者一个人长期使用bilili下载到同一个目录。比起翻代码，有一个统一的文件来改变应用的设置是很友好的（很抱歉我想象匮乏难以形容）

- 没明白 api 返回值与配置的关系
- 长期下载到同一目录，用 `alias` 就好了啊，看我最开始的那个例子，我觉得用得挺舒服的
- 更改默认参数也同上，用个 `alias` 解决一切

**Comment by loliconRoot** [comment]
的确，毕竟如果有需要可以给它套个包装...

**Comment by loliconRoot** [comment]
我仔细思考了一下，对于python脚本，配置文件主要作用突出在交互式接口下容许用户的设置跨启动保存，在不需要交互式接口下它的作用并不大。   
毕竟bilili的参数不是很多。（因为我打算写的爬虫功能有点多，所以下意识想要配置文件了）

**Comment by SigureMo** [comment]
嗯，我以前做交互式那会也会使用相似配置，不然一直输入会烦死，但自从不使用交互式以后就再也不需要考虑这些了～

**Comment by loliconRoot** [comment]
当我想写一个能爬多种网站上的小说，动漫和漫画以及搜索功能时，我发现我不得不采用交互式，就像这样：
```
Silisili>刀剑神域

刀剑神域动漫大全
===================================================================================================
id:0|标题:刀剑神域 Alicization War of Underworld
    |地区:日本
    |年代:2019年10月
    |标签:冒险,奇幻,战斗,爱情
    |播放:254354
    |看点:
    |简介:桐人、尤吉欧、爱丽丝。 两名修剑士与一名整合骑士，将最高司祭·亚多米尼史特蕾达击破后过了半年。 战斗结束，回到故乡卢利特村生活的爱丽丝。 她的身旁，是失去亲友、也失去自己的手臂与心的桐人。 ...
    |状态: 连载
    |PageID:2233

id:1|标题:刀剑神域III Alicization篇
    |地区:日本
    |年代:2018年10月
    |标签:科幻|游戏||冒险|动作
    |播放:1185669
    |看点:讲述了序列之争之后的故事。
    |简介:这里……是哪儿……？”如果注意到桐人、不知为什么陷入了庞大的空想虚拟世界。登陆前的记忆模糊不清，只得在周围徘徊寻找线索。之后，桐人到达了漆黑的大树“基加斯西达”并与一名少年相遇了。“我的...
    |状态: 连载
    |PageID:1864
```
...

**Comment by loliconRoot** [comment]
还有其他站点的单独搜索和联合搜索要做....

**Comment by SigureMo** [comment]
建立在搜索之上的话，倒不得不进行交互了

**Comment by loliconRoot** [comment]
就是这样

**Comment by loliconRoot** [comment]
你的下载器还真是神奇

**Comment by SigureMo** [comment]
并不是……以前是专用的，然后我各种解耦各种魔改，就成了现在这个样子

比较散乱，我倒是想将其整合成一个单独模块，但现在还没有比较好的方法

**Comment by loliconRoot** [comment]
我在为我的项目写一个下载器，因为功能太杂就参考了一下IDM

**Comment by loliconRoot** [comment]
然后发现如果我不是想写一个下载器而是把它作为一个模块的话，没什么大用

**Comment by SigureMo** [comment]
如果不是下载大文件的话，确实下载器没什么用，但 B 站视频动辄几个 G，所以我这里还是有点必要的

**Comment by SigureMo** [comment]
我倒是试过调用 Aria2，但与其交互处理不太好，而且速度不是很快，还不稳定，所以就放弃了，当然也许是我调用方式不当

**Comment by loliconRoot** [comment]
可能是headers的问题，命令行传不过去一些参数

**Comment by loliconRoot** [comment]
比如有些文件需要通过浏览器中的插件传递参数才能下载，直接复制链接就不行

**Comment by SigureMo** [comment]
我看了下，当时我用了 user-agent 和 referer，不然的话连下载都下不了的

**Comment by SigureMo** [comment]
这个我在我的实现里和 aria2 使用的是同样的参数，但 aria2 就是不太稳定

**Comment by SigureMo** [comment]
当然也许是当时网络的问题，后来我也没详细测试

**Comment by loliconRoot** [comment]
说不定是cookies的问题？？？抽空抓包分析一下

**Comment by SigureMo** [comment]
不会啊，我给他俩传相同参数，都没有 cookie

**Comment by loliconRoot** [comment]
好像还有的网站反多线程

**Comment by loliconRoot** [comment]
requests.session()?

**Comment by loliconRoot** [comment]
requests会自动补全不少参数，建议你用wireshark之类的软件查一查

**Comment by SigureMo** [comment]
session……可是我也是每个线程一个session啊……因为session不是线程安全的

**Comment by loliconRoot** [comment]
我看到了...跳来跳去找到底发现你和我说的不是一个session

**Comment by SigureMo** [comment]
我说的就是 requests.Session() 啊

**Comment by loliconRoot** [comment]
class Crawler(requests.Session)...
class BililiCrawler(Crawler)....
spider = BililiCrawler()....
spider.clone ....

**Comment by SigureMo** [comment]
对啊，每个线程一个clone啊，其实原来我不知道不是线程安全时所有线程使用的是同一个session，所以后来修改时候就直接使用的 clone

**Comment by loliconRoot** [comment]
（个人看法可能有误，仅供参考）tools里的spider是全局的，session会跨请求保持状态，在clone之前调用api中的函数使其得到了某种状态，在clone时状态被clone所以所有线程都持有了这种状态。

**Comment by SigureMo** [comment]
不会啊，clone是我自己处理的，不是session自带的函数，需要的参数我严格过滤了

**Comment by loliconRoot** [comment]
我测试了一下，但是还是有点怀疑self.__class__()的作用，资料也没找到....
简单的测试表明self.__class__()返回一个与self完全相同的副本，但是在内存的不同位置，是这样吗？

**Comment by loliconRoot** [comment]
话说clone不是没有影响到父类吗，那个影响储存在requests.session()里，至少你处理的代码没有影响到父类，但是之后有可以调用父类中的方法，说明clone对父类不产生影响....(我是这样想的)

**Comment by SigureMo** [comment]
`self.__class__` 就是 `self` 这个对象的类，也就是`BililiCrawler`，这里相当于完全新建了一个对象，并不是 copy，所以内存里是否一样取决于 Session 内部的初始化方式

父类是指什么，两个对象怎么会通过父类交互呢？

我这里就相当于创建了两个 session 对象，如果他们之间有影响，那么就是 session 的设计问题了

**Comment by SigureMo** [comment]
总觉得讨论偏了呢，还有你还不睡吗Σ(ﾟ∀ﾟﾉ)ﾉ

**Comment by loliconRoot** [comment]
我刚才明白过来了，之前是我错了，没绕过来

**Comment by loliconRoot** [comment]
今天中午才能睡

**Comment by SigureMo** [comment]
？？？

**Comment by SigureMo** [comment]
然后晚上起？

**Comment by loliconRoot** [comment]
今天是教师节，看望一下我一个老师，之后见着就难了

**Comment by loliconRoot** [comment]
不一定，说不定是下午

**Comment by loliconRoot** [comment]
让我再在你的中间类里绕一绕

**Comment by SigureMo** [comment]
emmmm，别绕了，是我设计的问题

**Comment by loliconRoot** [comment]
如果不饶我改不了啊（哭脸）

**Comment by SigureMo** [comment]
别看了别看了，代码写那么烂我都无地自容了( ๑ŏ ﹏ ŏ๑ )

**Comment by loliconRoot** [comment]
相信我，我的比你烂。你的文件架构合理，至于我的...一团浆糊

**Comment by SigureMo** [comment]
不行了，虽然不困但我也得睡了，不然作息会打乱（虽然本来就很乱

**Comment by loliconRoot** [comment]
今晚见，如果有发现我会留言的

**Comment by loliconRoot** [comment]
祝好梦，梦里没bug

**Comment by loliconRoot** [comment]
你的下载器（bilili.handlers）我吃明白了（指架构）。我有点说不下去，有空对线。

**Comment by loliconRoot** [comment]
一个下载器，在完全独立的情况下（抽象模型）应当是由主线程管理”下载文件条目“。在其作为模块的情况下，可以考虑略过“下载文件池”，以“下载文件条目”作为基本单位。但同样的，对于一个多线程下载器而言，“分块文件条目”都应当由下载器内部统一管理。当“分块文件条目”由外部管理时，也就是下载器内部没有一个统一的“下载文件条目（管理器）”（负责下载文件信息管理，文件分块，下载错误处理，文件合并，进度统计及显示等...）的object时，就会导致外部代码冗余，外部代码与下载器内部信息交流困难，下载器不独立等问题

**Comment by loliconRoot** [comment]
一个标准的下载器，外部程序应当告诉它：“从哪里下载（url），下载到哪里（path），保存为什么（filename）已及可选的seesion（提供必要的验证信息），是否显示进度条（同时可以通过接口告诉外部程序下载进度）等设置”。但也仅仅应当告诉它这些。其他的包括：“下载文件过小时应使用单线程下载，多线程下载时当一个线程下载完成时回收它或者分配新的下载任务，全部文件下载完成时将他们合并”

**Comment by loliconRoot** [comment]
简单的情况下，这可以通过创建一个DownloaderPool并向其中添加任务（以便调控同时最多下载任务数等...）或者创建一个Downloader并传递给它必要的参数来让其完成任务。  
复杂的的情况下，类似于IDM，包括历史下载文件、下载文件分类、已完成/未完成/全部、队列调控功能等....

**Comment by loliconRoot** [comment]
但是相同的，一个良好设计的下载器必须是独立的，对外部代码处于“黑箱”或“半黑箱”状态。像你这么做（从我分析的代码看来），只会弄得一团糟......(语气似乎不对？まぁいっか、これでいい)

**Comment by loliconRoot** [comment]
而且你的中间件接口也有问题，算了，等你在的时候对线

**Comment by SigureMo** [comment]
哭了哭了 被看光了(*꒦ິ⌓꒦ີ)

**Comment by SigureMo** [comment]
但……你说的我都知道 实现呢？有什么好的实现方法吗

**Comment by loliconRoot** [comment]
来自还没睡醒就被拉去往天花板上贴壁纸的人的怨念.....盯~~~  
举个栗子，在一般的建筑施工中，甲方是投资方，乙方是施工方。乙方是包工头式的公司：公司下属有数个小组，公司给小组分配任务，小组将施工进度汇报给公司，再由公司统计整理后汇报给甲方。所有的小组不一定进行同一个任务，比如1、2组进行项目A，3、4、5组进行项目B。  
而你的代码就没有乙方，甲方直接给原乙方下属的小组分配任务并汇总进度，而且所有的甲方都要这样做。就好比这个世界没有建筑公司取而代之的是每个公司都有一个“建筑部”一样.....这显然是不合理的

**Comment by SigureMo** [comment]
我知道啊 我没说我的合理啊

**Comment by loliconRoot** [comment]
而且中间件和‘内部’下载器的分离也是一个打问题，用多叉树做线程管理无可厚非（具体你这么做的我也没看，但是我这有一个多叉树管理多线程模式的设计。），毕竟它适于“当一个线程下载完成时将另一个线程没有下载完成的部分进行再分配”的情况，但是你的代码中似乎一个线程下载块大小是固定的，所以简单地也可以采用pool模型（不过我还是比较推荐使用多叉树，因为这样分隔块是一个很好的选择）

**Comment by loliconRoot** [comment]
哈哈（くさ）

**Comment by loliconRoot** [comment]
最基础的，可以考虑先实现一个代表‘下载文件’的类 ，并将其作为下载文件的管理者

**Comment by SigureMo** [comment]
是指单个文件还是整个下载器

**Comment by loliconRoot** [comment]
> 简单的情况下，这可以通过创建一个DownloaderPool并向其中添加任务（以便调控同时最多下载任务数、全部开始/全部停止等...）或者创建一个Downloader并传递给它必要的参数来让其完成任务。

指上面的Downloader

**Comment by loliconRoot** [comment]
它既可以是整个下载器，也可以通过一个pool来包装它以实现更多功能

**Comment by SigureMo** [comment]
那么怎么与外部合并事件挂钩呢，我的合并事件是需要知道当前下载片段所在内容全部完成时执行

**Comment by loliconRoot** [comment]
同时一个Downloader实体，也代表了一个独立的下载文件  
Downloader <==> downloadfile

**Comment by loliconRoot** [comment]
Downloader实体，记录了所有的下载文件的信息，同时通过对文件头（http headers）的读取，判断是采用大文件的下载方式（多线程）还是小文件的下载方式（直接下载）。当目标是大文件是，它为下载线程分配任务并激活线程，处理一些简单的有可能发生的错误，并等待所有线程执行完成后进行合并

**Comment by loliconRoot** [comment]
Downloader是文件的整体，而你的RemoteFile类更像文件的一个分块，是下载线程的实例。具体来说，由一个Downloader创建数个子RemoteFile并分配下载任务给它们

**Comment by loliconRoot** [comment]
一个Donwnloader的实例应该包括以下文件元数据：  
* 文件名
* 保存路径
* 源url
* 认证
* 文件大小

而一个RemoteFile的实例还应该额外包括：
* 临时文件路径
* 已下载大小
* 被分配的任务（range）

**Comment by loliconRoot** [comment]
在吗....长时间不回话心里有点慌....

**Comment by SigureMo** [comment]
我知道，我原来的 RemoteFile 就是内部管理分块，但这必然导致一个问题，就是起内部有着两层结构（Media -> Block），而外部还有两层结构（Contanier -> Media），这样的话状态的管理需要内部管理 + 外部管理，这势必导致可维护性不强

我现在虽然结构比较松散，但统一在外面的三层结构导致整体逻辑梳理起来非常方便，这也是我为什么采用三层树结构的状态管理器

**Comment by loliconRoot** [comment]
这样不仅可以对下载器进行独立封装，提升可重用性，而且还提高了可维护性

**Comment by loliconRoot** [comment]
container

**Comment by loliconRoot** [comment]
实际上实现与接口分离是OOP的一个重要理念

**Comment by loliconRoot** [comment]
外部代码只需要管封装库所提供的接口，并知道这些接口的作用。 
同时内部实现不需要管外部代码是如何的，它只需要提供接口并实现这些接口的功能

**Comment by SigureMo** [comment]
这我都知道，但对 bilili 来说，内部两层，外部两层的结构并不适合她，因为那势必会导致内两层与外两层逻辑的重复，所以我将其统一成了三层结构，当然如果要将下载器完全独立出去只能将结构单个下载文件作为一个整体，但我觉得如果没有别人用的话我完全没必要去做这个，毕竟我的下载器只为 bilili 开发

**Comment by loliconRoot** [comment]
我先用你的代码写一个简单点的试试（话说你那里为什么有这么多重复的代码啊）

**Comment by SigureMo** [comment]
？？？哪里

**Comment by loliconRoot** [comment]
handlers <==> events
parser <==> video_parser
handlers.middleware <==> handlers.status

**Comment by loliconRoot** [comment]
内部两层，外部两层的结构?

**Comment by SigureMo** [comment]
？你看的是什么 pip？

**Comment by loliconRoot** [comment]
'''__main__.py'''里的代码太....所以我没有细看。

**Comment by SigureMo** [comment]
你居然在 pip 看的？pip 不能看代码，在 GitHub 看

**Comment by loliconRoot** [comment]
我最开始是pip search bili*才找到的bilili...

**Comment by loliconRoot** [comment]
这回好了，我就说嘛

**Comment by SigureMo** [comment]
越来越歪了，这个 issue 本来说的是啥来着？

**Comment by loliconRoot** [comment]
emmm，歪的好快

**Comment by SigureMo** [comment]
所以你现在是想做一个下载器是吗，如果真的想做的话，我可以把下载器抽出来作为一个项目，如果整体结构理想的话，我会将其用在 bilili，不过我的精力有限，后续维护相关可能没太多时间，这也是我为什么不将其抽成独立项目的原因，之后真的没太多时间维护的

**Comment by loliconRoot** [comment]
我先试一试吧，写完了让你把把关

**Comment by loliconRoot** [comment]
发现了一件神奇的事情....举个例子：
```https://www.bilibili.com/video/BV1WV411m7f4```
64个短视频的合集，然后：  
```requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.bilibili.com', port=80): Max retries exceeded with url: /x/web-interface/view?aid=&bvid=BV1WV411m7f4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219163A9C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))```

**Comment by loliconRoot** [comment]
```urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000219163A9C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
socket.gaierror: [Errno 11001] getaddrinfo failed
[warn] ~~~ 无法下载，原因：「-404」 啥都木有
bilili.api.exceptions.UnsupportTypeError: (104, 'Not support dash type')
```

```File "c:\program files\python38\lib\site-packages\bilili\api\acg_video.py", line 123, in get_acg_video_playurl
    if res.json()["data"]["dash"]["video"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by SigureMo** [comment]
无法复现

**Comment by loliconRoot** [comment]
我知道

**Comment by SigureMo** [comment]
啥都木有 重试即可，文档有说

**Comment by loliconRoot** [comment]
同样的命令，不同的结果，有意思  
正是因为这样，我的IP似乎被封了

**Comment by loliconRoot** [comment]
我是记得你说过IP被封的问题（笑）

**Comment by SigureMo** [comment]
？我说什么了

**Comment by SigureMo** [comment]
> 这个嘛，暂时只是针对 bilili 本身的，以其下载视频的频率我还没遇到过封 IP 的情况（不会你用这个都会被封了吧

正常按下一部番的频率不会被封

**Comment by loliconRoot** [comment]
哈哈，我知道的。就像你永远无法知道你的队友在怎样和你玩游戏的一样，你永远不知道的bilili会被用来下载什么（-$-）

**Comment by loliconRoot** [comment]
因为一些功能上的需要：
1. 更新弹幕
2. avi/bvi/上传时间/时长/标题，列表
3. 基础视频信息，包括标题/子标题/简介/作者/...
4. 视频封面
5. 一些其他的功能....

我可能需要修改/参考bilili的代码，基本上包括：
1. 修改下载器
2. 修改入口点为```main(vbideo_info,config)```以便其可以通过命令行调用的同时亦可以接受程序的调用
3. 建立自己的UI接口（用以提供更多的功能）

**如果这是不被允许的，请告知，我将重新构建全部的代码。**

---
ps：我的编程能力比较弱，而且最近有各种各样的事。所以我可能需要一段时间并且暂时不会来这里了。

**Comment by SigureMo** [comment]
尽可能每个功能作为一个 PR，我会 review，不一定 merge

**Comment by loliconRoot** [comment]
收到

**Comment by antatura** [comment]
呃。。。相比于 UI 我更喜欢命令行 o(￣▽￣)ｄ

**Comment by loliconRoot** [comment]
大学刚开学，正在军训，可能要再拖一拖
