### ISSUE TITLE
✨ 解析下载流的时候为什么要进行两次请求，是否可以合成一次请求

### ISSUE THREAD

**Issue by xincheng213618** [SigureMo/bilili#52]
解析下载流的时候为什么要进行两次请求，是否可以合成一次请求？
![image](https://user-images.githubusercontent.com/25397726/99146381-89a10f00-26b2-11eb-9983-61173dc278f5.png)
B站有防爬，为了更有效的进行下载，我重新对下载逻辑进行了调正，添加了数据库用来缓存相关接口保存的数据，在研究下载流的解析的时候发现，在获取流的时候要对流接口进行两次访问
见 billil/api/acg_video.py:
80        touch_message = spider.get(play_api.format(avid=avid, bvid=bvid, cid=cid, quality=80)).json()
81       if touch_message["code"] != 0:
            raise CannotDownloadError(touch_message["code"], touch_message["message"])

        accept_quality = touch_message["data"]["accept_quality"]
        for quality in video_quality_sequence:
            if quality in accept_quality:
                break

        play_url = play_api.format(avid=avid, bvid=bvid, cid=cid, quality=quality)
        res = spider.get(play_url)

为什么要获取accept_quality ？ 去除之后对下载的内容似乎不影响
在下载少数文件时，不影响，如果进行大量下载，多一个http 请求，必然会让接口更早的进行ip封锁

仅作为想法，不提供 PR

**Comment by SigureMo** [comment]
如果没记错的话，有时不使用 `accept_quality` 内的清晰度作为参数并不能返回想要的那个清晰度的视频链接。由于过去太久了详情我已记不清楚，但我可以确定这个是必要的。

关于大量请求……还是不要大量请求了，我平时在 debug 时候频繁请求都没有触发封锁，难以想象触发封锁是在下载些什么了……当然我也会尽可能减少不必要的请求。
