### ISSUE TITLE
🐛 会员番剧弹幕下载报错

### ISSUE THREAD

**Issue by MOIX-1192** [SigureMo/bilili#53]
## 调用方式
`bilili --danmaku xml www.bilibili.com/bangumi/media/md28230900`
报错信息
`视频地址有误！`

## 环境信息

-  OS： win10 教育版 1909
-  Python： 3.8.3
-  bilili：1.3.6
![Snipaste_2020-11-18_15-37-56](https://user-images.githubusercontent.com/19689668/99499581-14845100-29b4-11eb-9374-ab061f78154e.png)

## 是不是需要会员登陆后才能下载？

**Comment by SigureMo** [comment]
emmm 如果是下载大会员内容当然要登录啦 详情看文档里的[个人信息认证](https://bilili.sigure.xyz/guide/cli.html#%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF%E8%AE%A4%E8%AF%81)部分

但这里的报错不是因为这个，你的链接不满足规范，前面需要 http，满足规范的看文档

**Comment by MOIX-1192** [comment]
> emmm 如果是下载大会员内容当然要登录啦 详情看文档里的[个人信息认证](https://bilili.sigure.xyz/guide/cli.html#%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF%E8%AE%A4%E8%AF%81)部分
> 
> ~但这里的报错不是因为这个，你的链接不满足规范，前面需要 http，链接规范看文档~才看到你之前尝试了 http，那么就是认证问题了

好的，谢谢

**Comment by SigureMo** [comment]
对了建议使用 ass 喔，xml 的貌似只是传输用的没播放器支持
