### ISSUE TITLE
✨ 下载自动点赞加评论

### ISSUE THREAD

**Issue by xincheng213618** [SigureMo/bilili#54]
为了更好白嫖，理应给下载的视频点赞+评论
除了sessdata 还需要bili_jct 同样也在cookie 中获取
不提供PR ，仅提供想法

headers = {
    "cookie": "SESSDATA=; bili_jct="
}
bili_jct =""
SESSDATA =""

replayaddurl ="https://api.bilibili.com/x/v2/reply/add"
def replayadd(avid: str = "", bvid: str = "",message: str=""):
    replaydata = {
        "oid": avid,
        # "bvid": "BV1LK4y177wV",
        "type": "1",
        "message": message,
        "plat": "1",
        "ordering": "heat",
        "jsonp": "jsonp",
        "csrf": bili_jct
    }

    r = requests.post(replayaddurl, data=replaydata, headers=headers)
    return r.text

likeurl ="https://api.bilibili.com/x/web-interface/archive/like"
def like(avid: str = "", bvid: str = "",like:str ="1",):
    likedata = {
        "aid":avid,
        "bvid": bvid,
        "like": 1,
        "csrf": bili_jct
    }
    r = requests.post(likeurl, data=likedata, headers=headers)
    return r.text

**Comment by xincheng213618** [comment]
接口有峰值上限，单IP 封锁 50条/小时？？？？，反正挺少的

**Comment by SigureMo** [comment]
TL;DR:

**至少现在我觉得该功能还为时尚早，也许以后会改变想法。**

单就需求来看，感觉有点奇怪。因为明明在下载视频之前，copy 其 url 的时候就已经打开了这个可以点赞的页面，此时顺手点个赞就好了呀，至于评论就更不可行了，难道统一留一个 `bilili 到此一游`，这种无意义的评论也不是 UP 主想要看到的。

我认为 bilili 的定位暂且仅限于视频及相关资源的获取，而且不改变帐号的状态，如果增加了改变状态相关操作势必会增加整体逻辑复杂度，这是我不想看到的。

**Comment by xincheng213618** [comment]
嗯，B站的点赞和评论就是给接口发个数据就行，只是看了下其他人做的B站下载工具包里有这么一块，就顺手实现了一下

**Comment by xincheng213618** [comment]
手动狗头~
