### ISSUE TITLE
[Bug Report] dir option is invalid

### ISSUE THREAD

**Issue by MyNetdisk** [SigureMo/bilili#6]
-d/--dir 指定存储目录，默认为项目根目录

bilili.py
parser.add_argument("-d", "--dir", default=r"", help="下载目录")
大佬，这里怎么指定存储目录啊？请多指教

**Comment by SigureMo** [comment]
是不是出现指定的目录被改变了的问题了呀，比如绝对路径 `/home/movies/` 被改为相对路径 `homemovies` 如果你是遇到这个问题的话，是一个 bug，我这就 fix 下，稍等哦～

**Comment by SigureMo** [comment]
试试看现在可以了吗（修复 commit: d91b2c390cf01753efcb84b0cf473d741c4a7a01）

**Comment by MyNetdisk** [comment]
> 试试看现在可以了吗（修复 commit: [d91b2c3](https://github.com/SigureMo/bilili/commit/d91b2c390cf01753efcb84b0cf473d741c4a7a01)）



> 试试看现在可以了吗（[恢复](https://github.com/SigureMo/bilili/commit/d91b2c390cf01753efcb84b0cf473d741c4a7a01) commit：[d91b2c3](https://github.com/SigureMo/bilili/commit/d91b2c390cf01753efcb84b0cf473d741c4a7a01)）

可以啦，大佬。谢谢

**Comment by SigureMo** [comment]
嘻嘻，好哒～
