### ISSUE TITLE
运行出错🐛 

### ISSUE THREAD

**Issue by CXMANDTXW** [SigureMo/bilili#60]
安装一切正常，运行 bilili https://www.bilibili.com/video/BV1Sa4y1H7cy报错。

```
File "/Users/xxx/anaconda3/envs/bilbili/lib/python3.7/site-packages/bilili-1.3.6-py3.7.egg/bilili/__main__.py", line 144
    if (avid_match := regex.acg_video.av.origin.match(args.url)) or \
                   ^
SyntaxError: invalid syntax
```

## 环境信息

-  OS： mac catalina10.15.7
-  Python： Python 3.7
-  bilili： bilili 版本号
-  如果是显示相关问题
   -  Shell：Shell 类型
   -  Terminal：终端类型
-  Others： 其它信息

**Comment by SigureMo** [comment]
请使用 python3.8 及其以上版本
