### ISSUE TITLE
获取用户所有视频资料

### ISSUE THREAD

**Issue by AronWater** [SigureMo/bilili#67]
space.bilibili.com/ajax/member/getSubmitVideos 是biliutil用的一个接口
返回该用户所有视频资料， 但该接口下线了

请问这个bilili有能下载一个用户所有视频的函数吗？

**Comment by SigureMo** [comment]
现阶段的 bilili 没有对外提供下载的接口，也没有实现某个 UP 主的所有视频下载。

当然以后应该也不会233

**Comment by AronWater** [comment]
返回视频列表的json 数据估计是应该有？

**Comment by SigureMo** [comment]
> 返回视频列表的json 数据估计是应该有？

什么？没看懂

**Comment by AronWater** [comment]
就想找个接口
返回一个用户所有视频的每一个link 
然后就可以用你这个库把他们都下载了

**Comment by SigureMo** [comment]
这个接口，通过抓包就能获取，只不过想要用 bilili 来下载的话需要涉及源代码修改，因为 bilili 并未提供相关接口。
