### ISSUE TITLE
🐛 下载时 b 站提示登录通知

### ISSUE THREAD

**Issue by ouuan** [SigureMo/bilili#69]
## 调用方式

```bash
bilili -t flv -c "$(gpg --decrypt 2>/dev/null $HOME/.secrets/BILIBILI_SESSDATA.gpg)" https://www.bilibili.com/bangumi/media/md28231773
```

## 环境信息

-  OS： Arch Linux 5.10.9-zen1-1-zen
-  Python： Python 3.9.1
-  bilili： 1.3.6

## 问题简述

开始下载后，b 站消息通知：

![图片](https://user-images.githubusercontent.com/30581822/105835114-59f17a00-6006-11eb-95b1-4d2f824ef59e.png)

## 预期行为

如果可能的话，下载时不收到 b 站的登录提醒。

## 额外信息

不知道 bilili 有没有设置 User Agent 之类的，可能和这相关？

## 是否愿意为此贡献代码

还没仔细看源码，说不定可以（:dove:

**Comment by SigureMo** [comment]
咦？我这里没有这个问题呀……是每次使用 bilili 都会提示嘛？

**Comment by ouuan** [comment]
啊，dbq，我 sb 了，没看提醒的发送时间，貌似是我之前在隐私窗口登录的时候。 在网页版上看到计数增加我以为是新发的通知（
