### ISSUE TITLE
🐛 Lower case BV url does not work

### ISSUE THREAD

**Issue by ArchyCillp** [SigureMo/bilili#7]
B站的视频的url的bv大小写都是合法的（bv, BV），但是现在填写包含小写的bv号url会出错

比如：

python bilili.py https://www.bilibili.com/video/bv1Gi4y187Jh

视频地址有误！

**Comment by SigureMo** [comment]
咦，之前没有注意到呀，这个 url 是你从 B 站直接复制的嘛，我复制的貌似都是大写的

emm，小问题啦，回头我改一下这里～
