### ISSUE TITLE
✨ 希望能把CC字幕封装进MP4档里面

### ISSUE THREAD

**Issue by BraveSail** [SigureMo/bilili#70]
目前B站港澳台的番剧都是CC字幕，工具好像并没有把字幕下载下来，所以建议在ffmpeg合并的时候把字幕也封装进去，这样用potplayer之类的播放器打开就可以看了

**Comment by SigureMo** [comment]
麻烦给个有字幕的示例。

不过有将字幕直接嵌入到视频的必要吗？不嵌入也是能自动加载啊……

**Comment by BraveSail** [comment]
![Screenshot_2021-01-27-05-00-26-874_com bilibili app blue](https://user-images.githubusercontent.com/49320262/105904849-a36cb400-605c-11eb-82b3-5d6330797f98.jpg)

手机不方便将就着看吧，嵌入说的是内挂进去（mp4可以内挂字幕），如果放在外面得改成名字一样才可以自动加载，不过b站的字幕是bcc格式，要弄的话还得用bcc转srt工具转一下

**Comment by SigureMo** [comment]
那我解决下载这种字幕的问题不就好了？为什么还需要嵌入呢？

**Comment by BraveSail** [comment]
内封的话方便管理，复制到手机或者电视上直接就能加载，外挂两个文件比较麻烦，当然我就提个建议，我也可以自己手动内封

**Comment by SigureMo** [comment]
番剧字幕下载支持已于 #71 解决，可升级至 1.3.7 获取。

至于嵌入，暂不支持，也许以后、或者如果有下一个版本的话会支持。
