### ISSUE TITLE
请输入正确的房间号！

### ISSUE THREAD

**Issue by gao27024037** [SigureMo/bilili#72]
## 调用方式

```
C:\Users\GYL>bilibili https://www.bilibili.com/video/BV1vZ4y1M7mQ
请输入正确的房间号!

```

## 环境信息

-  OS： win10 20H2
-  Python： Python 3.9
-  bilili： bilili 版本号 不知 pip下的

## 问题简述

不论后面跟的网址是什么，都提示请输入正确的房间号！
我查了你的文档各处也没有相关信息，源码中也没有找到相关字段，不知道什么原因。
辛苦作者大大查一下错误。

**Comment by SigureMo** [comment]
> C:\Users\GYL>bilibili https://www.bilibili.com/video/BV1vZ4y1M7mQ

bilibili 是什么鬼？这是别的包吧？

**Comment by gao27024037** [comment]
> > C:\Users\GYL>bilibili https://www.bilibili.com/video/BV1vZ4y1M7mQ
> 
> bilibili 是什么鬼？这是别的包吧？

啊我错了，我看错了，我下了个什么鬼，不好意思
