### ISSUE TITLE
✨ 添加禁用弹幕下载的选项

### ISSUE THREAD

**Issue by necan** [SigureMo/bilili#8]
## 特性描述

有时候不需要下载弹模，但似乎没有开关，建议添加禁用弹幕下载的选项。

**Comment by SigureMo** [comment]
嗯，这个问题我也有在考虑，重构的新版本我会进行解决，master就暂时先不改啦，这两天抓紧把重构版弄稳定了，合并到master再说

**Comment by SigureMo** [comment]
Resloved by 3d63ea1f8
