### ISSUE TITLE
🐛 下载卡住在最后

### ISSUE THREAD

**Issue by XYZliang** [SigureMo/bilili#84]
## 调用方式

 ```bilili "https://www.bilibili.com/video/BV1vJ411a7xU" -c "914abd93%2*************C40ed1*a1"  --danmaku ass --disable-proxy```

## 环境信息

-  OS： Macos 11.3beta
-  Python： Python 3.9.1
-  bilili： bilili （pip安装的最新版）

## 问题简述

下载到最后时，进度条卡住长达30分钟仍没有进展，已排除网络问题
![image](https://user-images.githubusercontent.com/59312540/110203581-eadf2f00-7ea9-11eb-8baf-4dda89a119a2.png)
![image](https://user-images.githubusercontent.com/59312540/110203599-0c401b00-7eaa-11eb-809d-ebcb163f7aa9.png)

**Comment by SigureMo** [comment]
是每次都复现吗？可以用短视频测试一下

**Comment by XYZliang** [comment]
> 是每次都复现吗？可以用短视频测试一下

试了几次都一样。等我有空试一试短视频

**Comment by SigureMo** [comment]
emmm，应该也不是这个视频的问题，刚试了下是完全正常的，同 macOS 11.3beta :joy:
