### ISSUE TITLE
✨ 可否发布预打包的版本？比如用pyinstaller打包的命令行应用？

### ISSUE THREAD

**Issue by mo-han** [SigureMo/bilili#96]
主python环境是3.6版本的（不方便重装3.8的python，否则一堆第三方库还要再装，而且一定会有很多兼容性问题需要手动排查修复）。
于是就用不了bilili，但是又很想尝试，看着就很可爱不是嘛。
一个办法是用虚拟环境，另一个办法就是请作者直接发布一个自带3.8环境的预打包版本。
pyinstaller打包挺方便的，一条命令一般就行了，情况比较特殊的话也就多加几条命令，要不烦请您试试？

**Comment by SigureMo** [comment]
> 看着就很可爱不是嘛。

(๑>؂<๑）开心～

虽然很开心，但打包其实挺麻烦的，pyinstaller 打包的二进制文件应该是与架构与操作系统相关的吧，pyinstaller 应该也不方便交叉编译吧。因为我的开发主力机是 m1 mac（macOS + ARM64），相信我即便打包了也基本没人能用。而且一旦打包就一定要考虑跨平台，我是没有足够的机器来同时打包三个主流操作系统（macOS + Windows + Linux）* 两个主流架构（x86_64 + ARM64）的，一种貌似可行的方案是通过 GitHub Actions 来自动打包并 Release，具体怎么实施还是需要研究一下。

> 不方便重装3.8的python，否则一堆第三方库还要再装

我记得卸载重装的话库还在吧？兼容性的话倒确实有一点

> 一个办法是用虚拟环境

虚拟环境的可选方案还是蛮多的，用于 python 版本管理的 venv、miniconda，或者容器级的 Docker，也许以后会配置一个开箱即用的 Dockerfile 及镜像（2.0 也许会有）。
