### ISSUE TITLE
🐛 我同学第一次使用显示语法错误

### ISSUE THREAD

**Issue by sandlakecloudstack1** [SigureMo/bilili#97]
SynataxaError:invalid syntax

'apm_id_from' 不是内部或外部命令，也不是可运行的程序。
是不是那个ffmpeg的原因，他已经添加到环境变量了。
在我这边都可以，他那边不行，还需要重启电脑吗？

**Comment by SigureMo** [comment]
Python3.8及以上吗？

**Comment by sandlakecloudstack1** [comment]
与python版本有关吗
我看了看是3.7.4
，对了，是不是不用安装那个ffmpeg软件啊，直接下载好然后设置环境变量就行了，他安装了这个软件

**Comment by SigureMo** [comment]
> 与python版本有关吗

对的，最低支持 Python3.8，将来 2.0 甚至仅支持 3.9（也许会是 3.10）

> 对了，是不是不用安装那个ffmpeg软件啊，直接下载好然后设置环境变量就行了，他安装了这个软件

FFmpeg 居然还有可以安装的嘛？我貌似没有见过，就是下载后设置环境变量即可，之后打开任意终端（cmd、powershell、Windows Terminal）运行以下命令

``` cmd
ffmpeg -version
```

如果此时显示的不再是类似于什么「找不到 ffmpeg」这样的提示的话，就说明「安装」成功了

详情的话，文档有「详细操作的」 <https://bilili.nyakku.moe/guide/getting-started.html#%E6%88%91%E7%9A%84%E4%BE%9D%E8%B5%96-ffmpeg>

**Comment by sandlakecloudstack1** [comment]
是的，我的电脑上的python是3.8.5,可以使用bilili，谢谢了，找到问题了

**Comment by SigureMo** [comment]
(๑>؂<๑）
